export { default as RocketLaunch } from '../assets/icons/RocketLaunch.svg';
export { default as Logo } from '../assets/logo.png';
export { default as Menu } from '../assets/icons/nav_menu.svg';
export { default as Placeholder } from '../assets/Image Placeholder.png';
export { default as avatar16 } from '../assets/avatars/avatar_16.svg';
export { default as Collection_1 } from '../assets/collection/Primary Photo Placeholder.png';
export { default as SubCollection_1 } from '../assets/collection/Secondary Photo Placeholder (1).png';
export { default as SubCollection_2 } from '../assets/collection/Secondary Photo Placeholder.png';
export { default as SubCollection_Number } from '../assets/collection/Number of additional NFTs.png';
export { default as CategoryImage_1 } from '../assets/categories/images/Image Placeholder.png';
export { default as CategoryIcon_1 } from '../assets/categories/icons/PaintBrush.svg';
export { default as DiscoverImage_1 } from '../assets/discover/Image.png';
export { default as BannerMashroom } from '../assets/ScreenTablet.png';
export { default as InfoCardIcons1 } from '../assets/infoIcons/Setup Wallet Icon1.png';
export { default as Widget1 } from '../assets/Photo1.png';
export { default as Widget_Desktop } from '../assets/Photo-desktop.png';
